export default class Item {
    lyric: string;
    furigana: string;
    index: number;
    length: number;
    start: number;
    end: number;
    constructor(lyric: string, furigana: string, index: number, length: number, start: number, end: number) {
        this.lyric = lyric;
        this.furigana = furigana;
        this.index = index;
        this.length = length;
        this.start = start;
        this.end = end;
    }

    get pattern() {
        const patterns = [
            [
                "あ",
                "か",
                "が",
                "さ",
                "ざ",
                "た",
                "だ",
                "な",
                "は",
                "ば",
                "ぱ",
                "ま",
                "や",
                "ら",
                "わ",
                "ア",
                "カ",
                "ガ",
                "サ",
                "ザ",
                "タ",
                "ダ",
                "ナ",
                "ハ",
                "バ",
                "パ",
                "マ",
                "ヤ",
                "ラ",
                "ワ",
            ],
            [
                "い",
                "き",
                "ぎ",
                "し",
                "じ",
                "ち",
                "ぢ",
                "に",
                "ひ",
                "び",
                "ぴ",
                "み",
                "り",
                "イ",
                "キ",
                "ギ",
                "シ",
                "ジ",
                "チ",
                "ヂ",
                "ニ",
                "ヒ",
                "ビ",
                "ピ",
                "ミ",
                "リ",
            ],
            [
                "う",
                "く",
                "ぐ",
                "す",
                "ず",
                "つ",
                "づ",
                "ぬ",
                "ふ",
                "ぶ",
                "ぷ",
                "む",
                "ゆ",
                "る",
                "ウ",
                "ク",
                "グ",
                "ス",
                "ズ",
                "ツ",
                "ヅ",
                "ヌ",
                "フ",
                "ブ",
                "プ",
                "ム",
                "ユ",
                "ル",
            ],
            [
                "え",
                "け",
                "げ",
                "せ",
                "ぜ",
                "て",
                "で",
                "ね",
                "へ",
                "べ",
                "ぺ",
                "め",
                "れ",
                "エ",
                "ケ",
                "ゲ",
                "セ",
                "ゼ",
                "テ",
                "デ",
                "ネ",
                "ヘ",
                "ベ",
                "ペ",
                "メ",
                "レ",
            ],
            [
                "お",
                "こ",
                "ご",
                "そ",
                "ぞ",
                "と",
                "ど",
                "の",
                "ほ",
                "ぼ",
                "ぽ",
                "も",
                "よ",
                "ろ",
                "を",
                "オ",
                "コ",
                "ゴ",
                "ソ",
                "ゾ",
                "ト",
                "ド",
                "ノ",
                "ホ",
                "ボ",
                "ポ",
                "モ",
                "ヨ",
                "ロ",
                "ヲ",
            ],
            ["ん", "っ", "ン", "ッ"],
            ["ー"],
        ];
        return ((index) => (index === -1 ? 5 : index))(
            patterns.findIndex((pattern) => pattern.includes(this.furigana))
        );
    }
}
